//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DecorSellerEntities2 : DbContext
    {
        public DecorSellerEntities2()
            : base("name=DecorSellerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductSeller> ProductSellers { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<SellerOrderDetail> SellerOrderDetails { get; set; }
        public virtual DbSet<SellerOrder> SellerOrders { get; set; }
        public virtual DbSet<SellerCustomer> SellerCustomers { get; set; }
        public virtual DbSet<SellerPayment> SellerPayments { get; set; }
        public virtual DbSet<SellerShippingDetail> SellerShippingDetails { get; set; }
        public virtual DbSet<SellerPaymentType> SellerPaymentTypes { get; set; }
    }
}
