//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerPaymentType
    {
        public SellerPaymentType()
        {
            this.SellerPayments = new HashSet<Payment>();
        }
        public int PayTypeID { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Payment> SellerPayments { get; set; }
    }
}
